services:
  web:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - TZ=Asia/Karachi
    depends_on:
      db:
        condition: service_healthy
    networks:
      - logitrack_net

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Karachi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount your DDL script here to automatically create tables on first run
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - logitrack_net

networks:
  logitrack_net:

volumes:
  postgres_data: